name: phum_assocation
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bot_toast: ^4.1.3
  easy_localization: ^3.0.7
  upgrader: ^9.0.0
  flutter_svg: ^2.0.10+1
  photo_view: ^0.15.0
  http: ^1.1.0
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  flutter_app_badger: ^1.5.0
  connectivity_plus: ^6.0.3
  fluttertoast: ^8.2.5
  vibration: ^1.8.4
  intl: ^0.19.0
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  capped_progress_indicator: ^0.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/translations/        
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

